# Generated by Django 2.2.5 on 2019-09-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20190925_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Не подтвержденно'), (2, 'Подтвержденно')], default=1, max_length=2)),
                ('list_products', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
