# Generated by Django 2.2.5 on 2019-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Не подтвержденно'), (2, 'Подтвержденно')], default=1, max_length=255),
        ),
    ]
