# Generated by Django 2.2.5 on 2019-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190925_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Не подтвержденно'), ('Y', 'Подтвержденно')], default='N', max_length=255),
        ),
    ]
